<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE music [
	<!ELEMENT music (set+)>
	<!ELEMENT set (song+)>
	<!ELEMENT song EMPTY>
	<!ATTLIST set name ID #REQUIRED>
	<!ATTLIST song href CDATA #REQUIRED>
]>
<music>
	<!-- Okay. To use these, I plan to have PlayMusic() or whatever I called it take "set://" as a parameter, and return the actual file chosen.
	
	That way, if a board is supposed to have a constant song, it can have its Music property changed.
	That is, if the board's Music property is "set://Town", PlayMusic will pick a track from that set and return the name, and the board's Music property is set to "Caramel - Karamel Special K.s3m", so that next time you visit that board, the same song will return.
	
	In general, if a set is requested and we're already playing a song from that set, nothing should happen:
	
	if request is not a set
		queue request and start fade out
		current set is ""
		current track is request
	else
		if current set is request
			do nothing
		else
			queue random pick from requested set and start fade out
			current set is request
			current track is what we picked

	Then, when a song ends, we can check if it was from a set and pick another one from the same.
	For example, we're in a grasslands area and "Mozarella Filofox" just finished playing. We already know it's the Grasslands set, so we pick another one from the same: "I Don't Know So I Don't Care".
	If a set has only one entry, don't bother picking - just repeat the one.
	
	If a random pick from a set doesn't exist, remove it from the set and try again.
	If the set is empty, just play nothing.
 	-->
	<set name="Title">
		<song href="loonie_-_cronologie_4_remix.xm" />
	</set>
	<set name="Grassland">
		<song href="ko0x_-_gias_rush.it" />
		<song href="ko0x_-_idksidc.it" />
		<song href="joule-mozarella_filofox.xm" />
		<song href="aa-molec.s3m" />
		<song href="hyo-dum.it" />
	</set>
	<set name="Desert">
		<song href="ko0x_-_btto.it" />
		<song href="computer_weekend.mod" />
		<song href="robric600.xm" />
		<song href="serpent_-_my_dream.xm" />
		<song href="C3INTRO.MOD" />
	</set>
	<set name="Snow">
		<song href="ko0x_-_snowmans_land.xm" />
		<song href="crizz_-_milkyway.xm" />
		<song href="_hh_vibes.mod" />
		<song href="_x_1.mod" />
		<song href="beek-ita.it" />
	</set>
	<set name="Swamp">
		<song href="ko0x_-_zenon.xm" />
		<song href="ko0x_-_idksidc.it" />
		<song href="humpin.xm" />
		<song href="serpent_-_my_dream.xm" />
		<song href="8bit_party.it" />
	</set>
	<set name="Town">
		<song href="cutegg.it" />
		<song href="ko0x_-_gizgame_level1.it" />
		<song href="cutesy1v2.mod" />
		<song href="serpent_-_my_dream.xm" />
		<song href="caramel_-_karamel_special_k.s3m" />
		<song href="ub-ihni.it" />
	</set>
	<set name="Dungeon">
		<song href="i_like_your_atari.xm" />
		<song href="jumping-499.xm" />
		<song href="insan-01.s3m" />
		<song href="MRKMAGIC.s3m" />
		<song href="a0-insnej.xm" />
		<song href="computer_weekend.mod" />
		<song href="strobe_-_crystal_tears.xm" />
		<song href="409920kb.s3m" />
	</set>
	<set name="Shenanigans">
		<song href="joule-littlewe_kladdcakes.xm" />
		<song href="karbofos_-_1.xm" />
		<song href="lepra_-_high_on_popcorns.xm" />
		<song href="rubber.xm" />
		<song href="robric993.xm" />
		<song href="crizz_-_milkyway.xm" />
		<song href="8bit_party.it" />
	</set>
	<set name="Combat">
		<song href="jumping-499.xm" />
		<song href="INSAN-03.s3m" />
		<song href="fixedsys.xm" />
		<song href="i_like_your_atari.xm" />
		<song href="mathcexam.it" />
	</set>
	<set name="Victory">
		<song href="joule_-_rainbow.xm" />
		<song href="ko0x_-_without_you.xm" />
		<song href="dynamite_-_over_the_top.s3m" />
	</set>
</music>
