<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE biomes [
	<!ELEMENT biomes (realm+)>
	<!ELEMENT realm (biome+)>
	<!ELEMENT biome (groundGlyphs?, encounters?, cultures?, darken?)>

	<!ELEMENT groundGlyphs (#PCDATA)>
	<!ELEMENT encounters (#PCDATA)>
	<!ELEMENT cultures (#PCDATA)>
	<!ELEMENT darken EMPTY>

	<!ATTLIST realm
		id ID #REQUIRED
	>
	<!ATTLIST biome
		name CDATA #REQUIRED
		color CDATA #REQUIRED
		music CDATA #IMPLIED
		isWater CDATA #IMPLIED
		canBurn CDATA #IMPLIED
	>
	<!ATTLIST encounters
		max CDATA #IMPLIED
	>
	<!ATTLIST darken
		plus CDATA #REQUIRED
		div CDATA #REQUIRED
	>
]>
<!-- Okay, here's the low-down on what I'm planning. By default, all of these will have {  , ' ` .  } as their "grass".
But I'm gonna allow a <groundGlyphs> element to overrule that. Why an element? Because that lets us use ".
Other things that could be added are what kind of (fixed) clutter can be found here, and what kind of creatures. -->
<biomes>
	<realm id="Nox">
		<biome name="Water" color="#00007F" isWater="true" />

		<biome name="Tundra" color="#E6F3F2" music="set://Snow">
			<groundGlyphs>&#x2591;&#x201E; ~/</groundGlyphs>
			<encounters max="10">imp, imp, wild_dog, imp</encounters>
		</biome>
		<biome name="Grass Desert" color="#92B683" music="set://Desert" canBurn="true">
			<encounters max="10">wild_dog, canine, canine, goblin, slime</encounters>
		</biome>
		<biome name="Desert" color="#D2CB98" music="set://Desert">
			<encounters max="10">snake, snake, naga, naga, naga, slime, imp</encounters>
		</biome>
		<biome name="Taiga" color="#B7D0C4" music="set://Snow" />
		<biome name="Woods" color="#346A28" music="set://Grassland" canBurn="true" />
		<biome name="Savanna" color="#5D5E29" music="set://Grassland" canBurn="true" />
		<biome name="Forest" color="#3D772A" music="set://Grassland" canBurn="true" />
		<biome name="Seasonal Forest" color="#53852E" music="set://Swamp" canBurn="true" />
		<biome name="Swamp" color="#343B2C" music="set://Swamp" />
		<biome name="Rain Forest" color="#2D7722" music="set://Swamp" canBurn="true" />
	</realm>
	<realm id="Seradevari">
		<biome name="KoolAid" color="#B22222" isWater="true" />
		
		<biome name="Nether" color="#3D1607" music="set://Dungeon">
			<groundGlyphs>#x.-/~</groundGlyphs>
			<encounters max="10">foocubus, imp</encounters>
			<cultures>seradevar</cultures>
			<darken div="1" plus="2"/>
		</biome>
	</realm>
</biomes>