<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE costumes [
	<!ELEMENT costumes (costume+)>
	<!ELEMENT costume (#PCDATA)>
	<!ATTLIST costume id ID #REQUIRED>
]>
<costumes>
	<costume id="school_uniform">
		<![CDATA[
male
random
	option
		plain_boxers
	option
		plain_briefs
boys_uniform_top
shirt
pants
female
random
	option
		plain_panties
		plain_bra
	option
		lacy_panties
		lacy_bra
blouse
girls_uniform_top
pleated_skirt
		]]>
	</costume>

	<costume id="casual">
		<![CDATA[
male	
setvar
	id: 1
	value: oneof blue, black, red, cyan, white, gray
random
	option
		plain_boxers
	option
		plain_briefs
shirt
	color: var 1
pants
female
setvar
	id: 1
	value: oneof blue, black, red, cyan, white, gray
random
	option
		plain_panties
		plain_bra
	option
		lacy_panties
		lacy_bra
random
	option
		random
			option
				shirt
					color: var 1
			option
				blouse
					color: var 1
		random
			option
				skirt
			option
				pants
	option
		random
			option
				sundress
					color: var 1
			option
				elegant_dress
					color: var 1
		]]>
	</costume>

	<costume id="lacy_undies">
		<![CDATA[
female
lacy_panties
lacy_bra
		]]>
	</costume>

	<costume id="bikini">
		<![CDATA[
female
bikini_top
bikini_bottom
		]]>
	</costume>

	<costume id="dress_test">
		<![CDATA[
female
random
	option
		plain_panties
		plain_bra
	option
		lacy_panties
		lacy_bra
random
	option
		elegant_dress
	option
		sundress
	option
		skimpy_dress
		]]>
	</costume>

	<costume id="lena">
		<![CDATA[
female
strapless_leather_bra
	color: black
kinky_panties
	color: black
knee_socks
	color: black
high_heels
	color: black
		]]>
	</costume>
</costumes>
