<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scenes [
	<!ELEMENT scenes (scene+)>
	<!ELEMENT scene (filter*,(p|script)*,action*)>
	<!ELEMENT filter EMPTY>
	<!ELEMENT p (#PCDATA)>
	<!ELEMENT script (#PCDATA)>
	<!ELEMENT action EMPTY>
	<!ATTLIST scene
		id CDATA #REQUIRED
		name CDATA #REQUIRED
		list CDATA #IMPLIED
	>
	<!ATTLIST filter
		target (top|bottom) #REQUIRED
		type CDATA #REQUIRED
		name CDATA #IMPLIED
		value CDATA #IMPLIED
	>
	<!ATTLIST script type CDATA #FIXED "text/javascript">
	<!ATTLIST action name CDATA #REQUIRED>
]>
<scenes>

	<!-- TDM -->
	<scene id="WinAgainstNaga" name="(rape start)">
		<filter target="bottom" type="bodylev" name="naga" />
		<p>
			With less than savory plans for the defeated [b:title], you take stock of [b:name] and consider how you should take advantage.
		</p>
		<action name="get blowjob" />
		<action name="get eaten out" />
		<action name="fuck vagina" />
		<action name="ride cock vaginally" />
		<action name="ride cock anally" />
		<action name="never mind" />
	</scene>
	<scene id="BipedGetFellatio" name="get blowjob" list="Get a blowjob">
		<filter target="top" type="has" name="penis" />
		<filter target="top" type="hasnot" name="noarms" />
		<!-- Original text prescribes the bottom to have a human-like face -->
		<p>
			Smiling wickedly, you fish out your [t:cock] and calmly tell [b:name] that [b:he]'s going to show it a good time before pushing it up against the side of [b:his] face.
		</p>
		<p>
			Knowing full well that [b:he] isn't in any shape to be refusing you, the [b:title] opens up its mouth and accepts your phallus into [b:his] jaws.
		</p>
		<p>
			Now that you're inside [b:name], what to do next?
		</p>
		<action name="get blowjob facefuck" />
		<action name="get blowjob softly" />
	</scene>
	<scene id="BipedGetFellatioHardMode" name="get blowjob facefuck" list="Rough facefuck">
		<p>
			Grabbing ahold of the [b:title]'s head, you start to rapidly piston your [t:cock] in and out of [b:his] maw, casing [b:him] to sputter and gag around your length. [b:His] distress isn't your concern, only getting off at [b:his] expense.
		</p>
		<p>
			Feeling your peek approach, it's time to decide how to finish things off.
		</p>
		<action name="get blowjob cum in mouth" />
		<action name="get blowjob cum on face" />
	</scene>
	<scene id="BipedGetFellatioHardModeInside" name="get blowjob cum in mouth" list="Cum in their mouth">
		<p>
			You force your length in as far as it will go, and feel your release take you, right down the [b:title]'s throat leaving [b:him] no choice but to swallow everything you have to offer.
		</p>
		<p>
			Feeling thoroughly satisfied, you pull your [t:cock] out of the abused [b:title]'s mouth and let [b:him] fall to the ground, exhausted.
		</p>
		<script type="text/javascript">
			top.GetToken("climax").Value = 0;
			top.GetToken("stimulation").Value = 10;
		</script>
	</scene>
	<scene id="BipedGetFellatioHardModeOutside" name="get blowjob cum on face" list="Cum over their face">
		<p>
			Feeling a little merciful (or maybe you want to mark your prize), you pull your [t:cock] from the confines of [b:his] throat just as you feel your peak hit.
		</p>
		<p>
			For an instant, the [b:title] hesitates, looking at your [t:cock] before it squirts [b:him] in the eye, and you proceed paint [b:his] face white.
		</p>
		<p>
			Feeling thoroughly satisfied, you pull your [t:cock] out of the abused [b:title]'s mouth and let [b:him] fall to the ground, exhausted.
		</p>
		<script type="text/javascript">
			top.GetToken("climax").Value = 0;
			top.GetToken("stimulation").Value = 10;
		</script>
	</scene>
	<scene id="BipedGetFellatioSoftModeNaga" name="get blowjob softly" list="Let things play out">
		<filter target="bottom" type="has" name="tongue/long" />
		<p>
			When [b:he] just sits there for a few moments, you inform [b:him], in annoyance, to get on with it. Sighing softly, the [b:title] hesitantly starts to move your [t:cock] around in [b:his] mouth.
		</p>
		<p>
			You sigh in pleasure, and encourage [b:him]. Feeling bolder, [b:name] starts to use [b:his] long tongue on your length. [b:He] runs it up and down the sides a few times before wrapping his serpentine licker all the way around you, and pumping you almost like a hand would. The [b:title]'s natural ability with [b:his] tongue is more than enough to push you over the edge, and let loose the proof of your orgasm all over [b:name]'s cock sucking tool of choice.
		</p>
		<p>
			Satisfied, you pull back from your defeated foe, and let [b:him] fall to the ground exhausted.
		</p>
		<script type="text/javascript">
			top.GetToken("climax").Value = 0;
			top.GetToken("stimulation").Value = 10;
		</script>
	</scene>
	<scene id="BipedGetCunnilingus" name="get eaten out" list="Get some cunnilingus">
		<filter target="top" type="has" name="vagina" />
		<filter target="top" type="hasnot" name="noarms" />
		<!-- Original text prescribes the bottom to have a human-like face -->
		<p>
			With a malevolent glint in your eye, you ready your [t:pussy] for the upcoming fun and casually inform [b:name] just what [b:he]'s going to be doing for you.
		</p>
		<p>
			The [b:title] obviously realizes that [b:he] isn't in any shape to be fighting back, and gives a small nod.
		</p>
		<p>
			Now then, how to sate yourself?
		</p>
		<action name="eaten out faceride" />
		<action name="eaten out licked" />
	</scene>
	<scene id="BipedGetCunnilingusHardMode" name="eaten out faceride" list="Rough faceride">
		<p>
			You push [b:name] to the ground, and almost literally sit on [b:his] face. You move your hips back and forth a few times as you settle your [t:pussy] right over [b:his] mouth and start grinding yourself into [b:him].
		</p>
		<p>
			You don't even give the [b:title] a chance to get [b:his] mouth open to pleasure you, instead content to just drown [b:him] in your [t:pussy].
		</p>
		<p>
			You stop for a moment and lift off to see how [b:he] is doing. You let him gasp and cough for air a few times before getting back into the action. Finding a good rhythm, it isn't too long before your pleasure pops, and you pull back satisfied.
		</p>
		<p>
			Just in time to see [b:name] pass out from the abuse.
		</p>
		<script type="text/javascript">
			top.GetToken("climax").Value = 0;
			top.GetToken("stimulation").Value = 10;
		</script>
	</scene>
	<scene id="BipedGetCunnilingusSoftMode" name="eaten out licked" list="Get licked">
		<filter target="bottom" type="has" name="tongue/long" />
		<!-- As if yet unwritten. -->
	</scene>
	<scene id="TDMReconsider" name="never mind" list="Never mind">
		<p>
			You change your mind about raping the naga, and reconsider what you should do with it laying there.
		</p>
	</scene>
	<scene id="LoseAgainstNaga" name="(loss rape start)">
		<filter target="top" type="bodylev" name="naga" />
		<p>
			You look up exhausted to see the face of [t:name] looking down at you with a sick grin on [t:his] face..
		</p>
		<p>
			Looks like you're going to be the recipient of more than just some physical injuries from this [t:title].
		</p>
		<!-- Game chooses from the below. We can call letbottomchoose() in a script block to allow the player some choice in the matter. -->
		<action name="get forced to blowjob" />
		<action name="get forced to eat out" />
		<action name="get fucked in vagina" />
		<action name="get cock ridden with vagina" />
		<action name="get cock ridden with ass" />
	</scene>
	<scene id="LoseAgainstNagaForcedCunnilingus" name="get forced to eat out">
		<filter target="top" type="has" name="snaketail" />
		<filter target="top" type="has" name="vagina" />
		<p>
			[t:He] slowly wraps [t:his] body around you, coiling you up into a tight full-body serpentine embrace. When [t:he]'s done, all that's left free is your face.
		</p>
		<p>
			[t:He] then moves next to your face and gently whispers in your ear, "Time to get to work, [b:g:boy:girl]." before presenting you with [t:his] moistening [t:pussy].
		</p>
		<p>
			Now, time to decide if you'll give [t:him] the satisfaction or resist to the end.
		</p>
		<script type="text/javascript">
			letbottomchoose();
		</script>
		<!-- The script above lets the player choose between these. This is automatically reset. -->
		<action name="get forced to eat out okay" />
		<action name="get forced to eat out resist" />
	</scene>
	<scene id="LoseAgainstNagaForcedCunnilingusOkay" name="get forced to eat out okay" list="Engage in a good licking">
		<p>
			You heave a sigh, and give into the [t:title]'s demands. You open your mouth and tentatively lick at the folds of [t:his] slit. Moaning appreciatively, [t:name] starts to sensually sway [t:his] body and pushes [t:him]self closer to you giving you better access. Knowing what's expected of you, you start to eat [t:him] out in earnest.
		</p>
		<script type="text/javascript">
			<![CDATA[
				//Here's where it gets cool.
				var skill = bottom.GetSkillLevel("cunnilingus");
				if (skill < 1)
				{
					print("Your lack of skill at this doesn't seem to bother the [t:title] too much, [t:he]'s probably getting what [t:he] expects from [t:his] victims.\n");
					print("Before too long she puts her hands on the back of your head and grinds you into her face until she goes over her limit and sprays your face with her fluids.\n");
				}
				else if (skill < 3)
				{
					print("[t:He] gasps in surprise from your efforts and says with obvious pleasure, \"Oh, you've done this before, haven't you [b:g:boy:girl]? I'm so glad I caught a skilled pussy licker!\"\n");
					print("It's fairly obvious from both [t:his] words and [t:his] moans that you're a cut above the [t:title]'s usual victims, and the proof of that is spilling across your face in moments.\n");
				}
				else
				{
					print("[t:name] gasps in shock as you expertly navigate [t:his] [t:pussy], teasing every part in just the right way.\n");
					print("Rapid shivers of pleasure move up and down [t:his] body until finally [t:he] screams and cums hard on your quick tongue.\n");
				}
				bottom.IncreaseSkill("cunnilingus");
			]]>
		</script>
		<action name="naga loss finish" />
	</scene>
	<scene id="LoseAgainstNagaForcedCunnilingusNo" name="get forced to eat out resist" list="Refuse">
		<filter target="top" type="has" name="snaketail" />
		<p>
			You grit your teeth and keep your mouth clamped shut.  You aren't going to give her the pleasure of your final surrender. After it becomes obvious to the [t:title] that you aren't going to give [t:him] what [t:he] wants, [t:name] simply laughs at you and says, "That's okay [b:g:boy:girl], I can take what I want."
		</p>
		<p>
			[t:He] puts her hands on the back of your head, and forces it into her waiting [t:pussy]. With another wicked laugh, [t:he] starts to grind your face into [t:his] [t:pussy], causing you to gasp for breath. However, it is fairly clear that [t:he] doesn't care about your discomfort and simply continues to roughly rub [t:him]self all over your face, while you're helpless to resist inside [t:her] tight serpent grip.
		</p>
		<p>
			Finally you're given a chance to gasp for air, just as [t:his] orgasm hits you in the face, leaving you sputtering again.
		</p>
		<action name="naga loss finish" />
	</scene>
	<scene id="LoseAgainstNagaFinish" name="naga loss finish">
		<filter target="top" type="has" name="snaketail" />
		<p>
			Finished with you, [t:name] the [t:title] disentangles you from [t:his] coils and drops you on the ground still covered in [t:his] fluids before slithering away.
		</p>
		<!-- TODO: possibly rob and/or attack the player. TDM writes that the naga should despawn, but this could result in unique items being Lost Forever, so let's not do that. -->
		<script type="text/javascript">
			top.GetToken("climax").Value = 0;
			top.GetToken("stimulation").Value = 10;
		</script>
	</scene>

	

	<scene id="GenericImpliedWilling" name="(starting node)">
		<filter target="bottom" type="hasnot" name="willing" />
		<filter target="bottom" type="stat" name="carnality" value="70" />
		<p>
			For a moment, [b:name] considers shrugging you off, but thinks better of it... or worse.
		</p>
		<script type="text/javascript">
			bottom.AddToken("willing");
		</script>
		<action name="(starting node)" />
	</scene>
	<scene id="GenericUnwilling" name="(starting node)">
		<filter target="bottom" type="hasnot" name="willing" />
		<p>
			[b:name] does not seem interested in your advances.
		</p>
	</scene>

	<scene id="GenericFriendlyIntro" name="(starting node)">
		<filter target="top" type="value_lower" name="carnality" value="30-" />
		<filter target="bottom" type="value_lower" name="carnality" value="30-" />
		<filter target="top" type="value_lower" name="climax" value="10-" />
		<filter target="bottom" type="value_lower" name="climax" value="10-" />
		<p>
			You softly embrace [b:name] and kiss [b:him], fully intent on making this as good a time as any.
		</p>
		<p>
			As [b:he] stops to breathe and gaze into your eyes, you let your tongue invade [b:his] mouth and probe around. [b:He] moans into your mouth, urging you to continue your ministrations.
		</p>
		<action name="fondle breasts" />
	</scene>

	<scene id="GenericFriendlyFondleFemale" name="fondle breasts" list="Fondle breasts">
		<filter target="bottom" type="gender" value="female" />
		<!-- Should check for top clothing, but there's no such check yet. -->
		<p>
			You reach for [b:his] [b:breasts] and proceed to softly stroke them.
		</p>
		<script type="text/javascript">
			<![CDATA[
				var breasts = bottom.Path("breastrow[0]");
				if (breasts.Path("size").Value > 4)
					//E (Pillowy) or higher
					print("It takes you a while to reach [b:his] [b:nipples] at that speed, but you get there and ");
				else
					print("Shortly, you trace an ever smaller circle up to [b:his] [b:nipples] and");
				if (breasts.Path("/nipples/size").Value > 2)
					print("pull on");
				else
					print("teasingly rub");
				if (breasts.Path("lactation").Value > 2)
					print("them, spraying a bit of milk on your fingers.");
				else if (breasts.HasToken("fuckable"))
					print("them, softly stroking the increasingly moist hole on top.");
				else if (breasts.HasToken("canfuck"))
					print("them, exciting them into soft nipple-y erections.");
				else
					print("them.");
			]]>
		</script>
		<!-- Should recheck for and remove top clothing, but there's no such command yet. -->
		<action name="fondle breasts more" />
		<action name="suckle breasts" />
		<action name="venture downwards" />
	</scene>

	<scene id="GenericFriendlyVenture" name="venture downwards" list="Venture downwards">
		<filter target="bottom" type="gender" value="female" />
		<!-- Same deal as in GenericFriendlyFondleFemale, but for pants slot. -->
		<p>
			You slide your hands slowly down towards [b:name]'s [b:waist] and stroke [b:his] [b:hips], leaving [b:him] in expectation of what comes next.
		</p>
		<script type="text/javascript">
			<![CDATA[
				if (bottom.Path("vagina[0]/wetness").Value >= 2)
					print("You easily");
				else
					print("You teasingly rub [b:his] [b:pussy] until it becomes slick with [b:his] feminine juices. At the right moment, you ");
				print("slide a finger ");
				if (bottom.Path("vagina[0]/looseness").Value >= 3)
					print("or two ");
				print("inside [b:him], leaving your thumb to stroke [b:his] aching clit in a vaguely circular motion.");
			]]>
		</script>
		<script type="text/javascript">
			<![CDATA[
				print("Moaning softly under your ministrations, [b:name] reaches for your crotch, ");
				if (top.HasToken("penis"))
					print("looking at your [t:cock]");
				else if (top.HasToken("vagina"))
					print("looking at your [t:pussy]");
				print("with an increasingly lustful gaze.");
			]]>
		</script>
		<action name="blowjob" />
		<action name="handjob" />
		<action name="eat out" />
		<action name="put it in" />
		<action name="demodummy"/>
	</scene>
	<scene id="demodummy" name="demodummy" list="Be stupid enough to try and test handjobs while female">
		<p>lol</p>
	</scene>
	<scene id="eatout" name="eat out" list="Don't actually have an &quot;eat out&quot; option yet">
		<p>lol</p>
	</scene>

	<scene id="GenericFriendlyTooSmallToPutItIn" name="put it in" list="Put it in!">
		<filter target="top" type="gender" value="male" />
		<filter target="bottom" type="gender" value="female" />
		<!-- Need a way to use the area of the penis instead of just the length. -->
		<!-- Perhaps a filter that compares against the other participant's vaginal capacity? -->
		<filter target="top" type="value_lower" name="penis/length" value="6" />
		<p>
			As you disrobe, [b:his] face seems disappointed. "Sweetie, I know what you want," [b:he] begins, but you sense what [b:he]'s about to say. You shush [b:her] with a finger on her lip, but [b:he] continues. "But there is no way for either of us to enjoy this with such a ...slender tool."
		</p>
		<p>
			You sigh and put your clothes back on, your lust plummeting with her rejection. Surely there must be a way to get your size big enough to penetrate her properly?
		</p>
		<script type="text/javascript">
			top.GetToken("stimulation").Value = 0;
			top.GetToken("climax").Value = 0;
			bottom.RemoveToken("willing");
		</script>
		<!-- Dead end, stop the system. -->
	</scene>
	<scene id="GenericFriendlyTooBigToPutItIn" name="put it in" list="Jam it in!">
		<filter target="top" type="gender" value="male" />
		<filter target="bottom" type="gender" value="female" />
		<filter target="top" type="value_gteq" name="penis/length" value="24" />
		<p>
			As if [b:he] wasn't already uncertain by the bulge in your clothes, [b:his] face is that of slight disgust and amazement that put you off.
		</p>
		<p>
			"Oh, uh, Sweetie, I don't think that big boy will fit inside me, but if you'd like we could perhaps settle for a good massage?"
		</p>
		<p>
			[b:His] facial features light up with [b:his] idea, and you nod approvingly. After all, a handjob is nearly as refreshing as a normal fucking, so you aren't one to mind in the slightest.
		</p>
		<!-- Whatever we list the handjob scene as, it won't show up. It'll just become "==>" -->
		<action name="compromise handjob" />
	</scene>

	<scene id="GenericFriendlyRegularHandjob" name="handjob" list="Get a handjob">
		<filter target="top" type="gender" value="male" />
		<!-- Needs to be differentiated from the compromise handjob more. -->
		<p>
			[b:name] claps happily as you sit down. Your [b:cock] hangs in the wind while [b:he] leans down, [b:his] slender hands enticing you by crossing a few times on your cheeks before 'exploring' your chest and finding themselves in your well-endowed nether regions, gripping your [t:cock] like a cowgirl throwing her rope and pulling around it, and you appreciate [b:his] horseplay.
		</p>
		<!-- Should check for baldness. -->
		<p>
			Being too gentle wouldn't get either of you anywhere, and [b:he] recognizes this thoroughly. You would ask if [b:he]'s done this before, but your rational thoughts get eclipsed by [b:his] stimulating pressure and [b:he] begins to ease up somewhat, beginning [b:his] rocking motion and you can't help but to outreach a hand and run through [b:his] hair while [b:he]'s busy working away.
		</p>
		<action name="continue handjob" />
	</scene>
	<scene id="GenericFriendlyCompromiseHandjob" name="compromise handjob" list="Accept generous compromise">
		<filter target="top" type="gender" value="male" />
		<p>
			[b:He] immediately claps happily and you sit, your [t:l:penis/length] member hanging in the wind while [b:he] leans down, [b:his] slender hands enticing you by crossing a few times on your cheeks before 'exploring' your chest and finding themselves in your well-endowed nether regions, gripping your [t:cock] like a cowgirl throwing her rope and pulling around it, and you appreciate [b:his] horseplay.
		</p>
		<!-- Should check for baldness. -->
		<p>
			Being too gentle wouldn't get either of you anywhere, and [b:he] recognizes this thoroughly. You would ask if [b:he]'s done this before, but your rational thoughts get eclipsed by [b:his] stimulating pressure and [b:he] begins to ease up somewhat, beginning [b:his] rocking motion and you can't help but to outreach a hand and run through [b:his] hair while [b:he]'s busy working away.
		</p>
		<action name="continue handjob" />
	</scene>

	<scene id="GenericFriendlyContinueHandjob" name="continue handjob" list="Enjoy">
		<!-- Could need male bottom version. -->
		<filter target="bottom" type="gender" value="female" />
		<p>
			Between your grunts and [b:his] kissing on your chest, you have a relaxed state of mind while your body begins to heat up, especially in your crotch area. [b:name] seems to be enjoying it as well and you notice [b:he]'s dropped a hand from your stick and has begun fingering [b:him]self to officially join the party.
		</p>
		<!-- Again, check for baldness. -->
		<p>
			You see this as an opening to shift your hands from [b:his] glistening hair to [b:his] [b:breasts], cupping them and playing with them freely, [b:his] [b:nipples] becoming furiously erect from your erotic treatment while your "big boy" is engorged, and you can see your eventual climax forming on the horizon.
		</p>
		<action name="finish handjob" />
	</scene>
	<scene id="GenericFriendlyFinishHandjob" name="finish handjob" list="Kitaaaa!">
		<p>
			After some steamy minutes pass by, your face flushed with crimson and [b:g:his:hers] a tiny bit more, you can feel your cum making its way to your tip and you sigh heavily, watching your semen squirt out frantically and making a mess of yourself, though your lover doesn't seem to mind while [b:he] orgasms [b:him]self, making what you deem sexy moaning noises to mingle with your own sounds.
		</p>
		<p>
			[b:He] pulls away and you lie back some, wanting to do nothing but rest and fully experience the moment.
		</p>
		<action name="finish basking from handjob" />
	</scene>
	<scene id="GenericFriendlyBaskFromHandjob" name="finish basking from handjob" list="Get up ya pussy.">
		<p>
			[b:name] heaves [b:him]self into your arms while your member goes into its more modest flaccid state. You rub against [b:his] back lovingly and with generous grace; [b:his] head digging into your chest. "That was amazing," [b:he] finally admits, and you have nothing to say but agree.
		</p>
		<p>
			Afterwards you both stand up, exchange looks that can only signify that you two would be at it again sometime in the future and clothe yourselves, your encounter coming to a close.
		</p>
		<script type="text/javascript">
			bottom.RemoveToken("willing");
		</script>
		<!-- No actions. Dead end. -->
	</scene>

	<scene id="GenericFriendlyFuckings" name="put it in" list="J-J-JAM IT IN!">
		<filter target="top" type="gender" value="male" />
		<filter target="bottom" type="gender" value="female" />
		<!-- References being good at foreplay; skill check? -->
		<!-- Should maybe have a version to prevent non-fitting dicks... -->
		<p>
			You look upon [b:him] with passive lust and snatch [b:him] up in a tender embrace after discarding your equipment. The moment is now yours and [b:g:his:hers]; you have to say it's a wonderful feeling just standing there and slowly fondling [b:his] [b:breasts], occasionally encircling her [b:nipples] playfully. You seem to be quite good at foreplay and [b:he] returns the gesture with a kiss on the cheek.
		</p>
		<p>
			It doesn't take very long before your more baser human instincts start to itch on the recesses of your mind and you happily give into them, turning your babe around and reeling [b:him] into your lap, [b:his] clit rubbing against your [t:cock], which immediately perks upward in a knee-jerk reaction while [b:he] pulls you into a tender kissing session on your lips, and you grunt with pleasure.
		</p>
		<action name="come on put it in" />
	</scene>
	<scene id="GenericFriendlyFuckings2" name="come on put it in" list="Do it!">
		<p>
			Once you are finished with your teasing, [b:he] backs off your manhood and lets go of you, laying on the ground before you and tempting you with a seductive hand wave, [b:his] legs crossed in an well produced attempt to get you even more aroused and ready to have intercourse than you already visibly are.
		</p>
		<script type="text/javascript">
			<![CDATA[
				print("[b:He] eyes up your [t:l:penis/length] dick with a ");
				var dickLen = top.Path("penis[0]/length").Value;
				if (dickLen > 20)
					print("zealous");
				else if (dickLen > 16)
					print("content");
				else
					print("longing");
				print(" expression and you move swiftly to kneel down and grip [b:his] hips, pulling [b:his] love-hole onto your cock.");
			]]>
		</script>
		<p>
			Pleasure overwhelms you and [b:he] squeals like a little school girl, obviously just as excited as you are and you begin thrusting, [b:his] legs wrapping around your back. "Oh, yes; please - more!" [b:He] exclaims, and you oblige [b:him] in every sense of the word.
		</p>
		<action name="give her more man" />
	</scene>
	<scene id="GenericFriendlyFuckings3" name="give her more man" list="Oblige the lady">
		<p>
			Your movements ease themselves into creating a rhythm and you lose some sense of what's going on - for all you're concerned, you're delightfully having sex with your chosen mate, and that's all that matters in your pleasure-induced haze. [b:His] vagina's innards serve as a perfect receptacle for your love-organ, and you fail to resist any urges of being even somewhat restrained, instead finding yourself bucking like a bull in speed, hammering [b:him] completely and it seems like your body is pulsating from all of the sensations that are happening one after another.
		</p>
		<action name="give it to her baby aha aha" />
	</scene>
	<scene id="GenericFriendlyFuckingsClimax" name="give it to her baby aha aha" list="KITAAA!">
		<p>
			Suddenly, your tip (which was already wet with precum and lady fluids) floods with your semen, pouring into [b:name]'s womb while you make noises that aren't of your accord; rather instinctual responses to your orgasm, and [b:he] goes into that perfect state as well, [b:his] figure nearly entirely flushed with red. After calming yourself down you retract from [b:his] hole and your penis deflates, having served its purpose well while you still feel somewhat dazed but manage to find your grip on reality. [b:name] sits up, leaning on you and you pull [b:him] into a warm hug.
		</p>
		<p>
			Time seems to slow down considerably as your nuzzle [b:his] neck and [b:he] grazes your back, but you know that all wonderful things must end at some point and stand, putting your equipment back on to continue your adventure. You assure [b:him] you'll be back for more and [b:he] thanks you for your time with [b:him].
		</p>
		<script type="text/javascript">
			bottom.RemoveToken("willing");
		</script>
		<!-- Final dead end. -->
	</scene>

	

	<scene id="EmiTest" name="(starting node)">
		<filter target="bottom" type="name" name="Mitsuko Murakami" />
		<p>
			Your [t:cock] stirs as [b:name] looks deep in your &lt;c[t:T:eyes/color]>[t:t:eyes/color]&lt;c> eyes.
		</p>
	</scene>
	<scene id="MulticockTest1" name="(starting node)">
		<filter target="top" type="has" name="penis" value="1" />
		<p>
			Exactly one cock.
		</p>
	</scene>
	<scene id="MulticockTest2" name="(starting node)">
		<filter target="top" type="has" name="penis" value="2" />
		<p>
			Exactly two cocks.
		</p>
	</scene>
	<scene id="MulticockTest3" name="(starting node)">
		<filter target="top" type="has" name="penis" value="2+" />
		<p>
			Two or more cocks.
		</p>
	</scene>
	<scene id="DevStart" name="(starting node)">
		<filter target="bottom" type="gender" value="male" />
		<p>
			Development starting node, male bottom.
		</p>
		<p>
			Second paragraph.
		</p>
		<short>[t:name] triggers devstart.</short>
		<action name="dev action 1" />
		<action name="dev leave" />
	</scene>
	<scene id="DevStart2" name="(starting node)">
		<filter target="bottom" type="gender" value="female" />
		<p>
			Development starting node, female bottom.
		</p>
		<p>
			Second paragraph.
		</p>
		<short>[t:name] triggers devstart.</short>
		<action name="dev action 1" />
		<action name="dev leave" />
	</scene>
	<scene id="DevAction1" name="dev action 1" list="Do a jig">
		<p>
			Testing scripts...
		</p>
		<script type="text/javascript">
			print("Second paragraph from script.");
		</script>
		<action name="dev climax" />
		<action name="dev leave" />
	</scene>
	<scene id="DevClimax" name="dev climax" list="Test climax">
		<script type="text/javascript">
			top.GetToken("climax").Value = 20;
		</script>
		<action name="dev climax" />
		<action name="dev leave" />
	</scene>
	<scene id="DevLeave" name="dev leave" list="Leave">
		<p>Baibai</p>
	</scene>

	<scene id="FinalDestination" name="(starting node)">
		<p>If you can see this, all the other nodes failed. (Regular)</p>
	</scene>
	<scene id="FinalDestination2" name="(rape start)">
		<p>If you can see this, all the other nodes failed. (Rape)</p>
	</scene>
	<scene id="FinalDestination2" name="(loss rape start)">
		<p>If you can see this, all the other nodes failed. (Loss Rape)</p>
	</scene>
</scenes>